services:
  - type: web
    name: quantux-servicedesk-v4-dev
    env: python
    branch: v4-dev
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port  --app-dir backend
    envVars:
      - key: APP_ENV
        value: development
      - key: APP_VERSION
        value: v4.0.0-DEV
      - key: PORT
        value: 10000
